# Generated by Django 5.2.9 on 2026-09-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accommodation_admin_notes_accommodation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Official admin contact email for this college (e.g. xyz@svr.edu.in)', max_length=254),
        ),
        migrations.AddField(
            model_name='college',
            name='max_team_members',
            field=models.PositiveIntegerField(default=1, help_text='Maximum authorized team admin emails allowed (e.g. 1, 4, 6)'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Review remarks or feedback from college admissions committee'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CollegeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Authorized staff team email address (e.g. admissions@svr.edu.in)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_members', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.college')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('college', 'email')},
            },
        ),
    ]
