# Generated by Django 5.2.9 on 2026-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_college_admin_email_college_max_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='min_10th_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum Class X (10th) percentage required to apply', max_digits=5),
        ),
        migrations.AddField(
            model_name='college',
            name='min_12th_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum Class XII (12th / +2) percentage required to apply', max_digits=5),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='address',
            field=models.TextField(blank=True, verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_10_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Class X Percentage (%)'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_10_school',
            field=models.CharField(blank=True, max_length=255, verbose_name='Class X School / Board'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_12_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Class XII Percentage (%)'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_12_school',
            field=models.CharField(blank=True, max_length=255, verbose_name='Class XII School / Board'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_or_guardian_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Father / Guardian Name'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
