# Generated by Django 5.2.9 on 2026-09-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('PG', 'Paying Guest (PG)'), ('Flat', 'Flat / Apartment'), ('Hostel', 'Hostel')], max_length=20),
        ),
    ]
