# Generated by Django 5.2.9 on 2026-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='gmap_location',
            field=models.CharField(blank=True, help_text='Google Maps share link, embed code, or coordinates (e.g. 28.5450, 77.1926)', max_length=500, verbose_name='Google Maps Location'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, help_text='Optional external link or brochure URL for this course', max_length=500, null=True, verbose_name='Course Link / Syllabus URL'),
        ),
        migrations.AddField(
            model_name='university',
            name='gmap_location',
            field=models.CharField(blank=True, help_text='Google Maps share link, embed code, or coordinates (e.g. 28.5450, 77.1926)', max_length=500, verbose_name='Google Maps Location'),
        ),
    ]
