# Generated by Django 5.2.9 on 2026-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_college_gmap_location_course_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.CharField(blank=True, help_text='e.g. ₹14.80 LPA', max_length=60, null=True, verbose_name='Average Package (CTC)'),
        ),
        migrations.AddField(
            model_name='college',
            name='highest_package',
            field=models.CharField(blank=True, help_text='e.g. ₹44.00 LPA', max_length=60, null=True, verbose_name='Highest Package (CTC)'),
        ),
        migrations.AddField(
            model_name='college',
            name='median_package',
            field=models.CharField(blank=True, help_text='e.g. ₹12.50 LPA', max_length=60, null=True, verbose_name='Median Package'),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_highlights',
            field=models.TextField(blank=True, help_text='Key placement and corporate relations highlights (one per line)', null=True, verbose_name='Placement Cell Highlights'),
        ),
        migrations.AddField(
            model_name='college',
            name='placement_rate',
            field=models.CharField(blank=True, help_text='e.g. 96.4%', max_length=50, null=True, verbose_name='Placement Rate (%)'),
        ),
        migrations.AddField(
            model_name='college',
            name='summer_stipend',
            field=models.CharField(blank=True, help_text='e.g. ₹80,000 / mo', max_length=60, null=True, verbose_name='Highest Summer Stipend'),
        ),
        migrations.AddField(
            model_name='college',
            name='top_recruiters',
            field=models.TextField(blank=True, help_text='Comma-separated recruiter company names (e.g. Google, Microsoft, Amazon, Deloitte, Goldman Sachs)', null=True, verbose_name='Top Recruiters'),
        ),
        migrations.AddField(
            model_name='college',
            name='total_offers',
            field=models.CharField(blank=True, help_text='e.g. 820+', max_length=50, null=True, verbose_name='Total Job Offers'),
        ),
    ]
