# Generated by Django 5.2.9 on 2026-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_college_average_package_college_highest_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admission_close_date',
            field=models.DateField(blank=True, help_text='Last date to apply for admission (e.g. 2026-12-31)', null=True, verbose_name='Admissions Close Date (Opened Till)'),
        ),
        migrations.AddField(
            model_name='college',
            name='admission_open_date',
            field=models.DateField(blank=True, help_text='Date when admission applications open', null=True, verbose_name='Admissions Open Date'),
        ),
        migrations.AddField(
            model_name='college',
            name='admissions_status',
            field=models.CharField(choices=[('Open', 'Open for Admissions'), ('Closed', 'Admissions Closed')], default='Open', max_length=20, verbose_name='Admissions Status'),
        ),
    ]
