# Generated by Django 5.2.9 on 2026-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_college_admission_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='food_included',
            field=models.CharField(choices=[('Included', '3 Meals Included (Breakfast, Lunch & Dinner)'), ('Optional', 'Food Available (Optional)'), ('SelfCooking', 'Self Cooking / No Food Included')], default='Included', max_length=20, verbose_name='Food & Meals'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='gate_closing_time',
            field=models.CharField(default='10:30 PM', max_length=50, verbose_name='Gate Closing Time'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys Only'), ('Girls', 'Girls Only'), ('Co-ed', 'Co-ed / Anyone')], default='Co-ed', max_length=20, verbose_name='Resident Category'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='notice_period',
            field=models.CharField(default='1 Month', max_length=50, verbose_name='Notice Period'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Security Deposit (₹)'),
        ),
    ]
